[workspace]
members = [
    "uranus-kv", # key value store
    "uranus-p",  # sql parser
    "uranus-c",  # client binary
    "uranus-s"   # server
]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
thiserror = "1.0"
tracing ="0.1.34"
tracing-subscriber = { version = "0.3.11" }
bytes = "1"
